### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by olizilla** [tableflip/ipfs-webui-cra#3]
Add in https://github.com/storybooks/storybook support. As this is a create-react-app it should work out of the box.

Try out https://github.com/storybooks/storybook/tree/master/addons/a11y and see if it could be a good way for us to build accessible components.

**Comment by olizilla** [comment]
@hacdias do you want to try this out and experiment with a first draft of the file list item, a file list, and bread-crumb UI components, with story book fixtures, so we can develop them in isolation without having to load up the whole app.

**Comment by hacdias** [comment]
Moved to https://github.com/ipfs-shipyard/ipfs-webui/issues/656.
