### ISSUE TITLE
Repository Migration Plan

### ISSUE THREAD

**Issue by lidel** [tableflip/ipfs-webui-cra#5]
## Background

@diasdavid  raised concerns about feedback we may lose by staying within separate repo for too long:

```
205400       @daviddias │ lidel: olizilla why a new repo and not a PR
205401                  │ ?
205426                  │ fixed perms
210948           @lidel │ daviddias, we are worried about mixing issues related to old codebase with new one
211144                  │ its easier to keep them separate for now
212439       @daviddias │ lidel: use labels
212451                  │ and have an active plan to migrate
212457                  │ a ton of users follow webui
212506                  │ and have provided feedback + follow the discussions there
212521                  │ you are leaving them outside for creating a new repo
```

I know we started thinking about keeping this repo to avoid dealing with, but David has a good point, we may be losing a valuable source of feedback, we should plan accordingly. 

Below is a draft of a plan to migrate back to the original repo.

## Migration plan

_cc @ipfs-shipyard/gui: this is just a draft of a plan, things can be changed or reordered, any feedback will be appreciated,_

1. [x] Create `revamp` label at original repo for issues related to "New WebUI"
    - DONE: https://github.com/ipfs-shipyard/ipfs-webui/labels/revamp
1. [x] Move issues 
     - I propose we avoid creating issues in this repo, and use `revamp` label in original repo instead.
     - We may consider disabling Issues tab here and updating README about temporary nature of this repo 
1. [ ] Finalize Tech choices for new WebUI (https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/51)
1. [ ] Create a working prototype (TODO: clarify if it should be MVP with feature-parity, just a first screen, or just a boilerplate with tech choices in place)
1. [x] Move prototype to a `revamp` branch in original repo https://github.com/ipfs-shipyard/ipfs-webui
1. [x] Delete or Update README to point at [original repo](https://github.com/ipfs-shipyard/ipfs-webui) and Archive this one

Thoughts?
Perhaps it would be easier to just create `revamp` branch at the original repo and move everything there ASAP instead?

**Comment by hacdias** [comment]
I agree with moving everything there ASAP if we're going to work there.

**Comment by hacdias** [comment]
@ipfs-shipyard/gui I took the liberty of starting working on some points above ^^

**Comment by olizilla** [comment]
+1 for revamp branch and move asap

**Comment by hacdias** [comment]
New branch: https://github.com/ipfs-shipyard/ipfs-webui/tree/revamp

I think now we just need to close this issue, archive the repo and get on workin'

**Comment by lidel** [comment]
Thanks for quick move! I closed the issue, but  don't seem to have permission to archive. :thinking:

@diasdavid in spare moment, please archive this repo, we moved to the original one.  
(again, sorry for the noise!)

**Comment by victorb** [comment]
@lidel could you please follow the procedure from here https://github.com/ipfs/docs/issues/54#issuecomment-384107777 ? Once that's done, ping me and I'll make the repository read-only/archived.

**Comment by lidel** [comment]
@VictorBjelkholm I'd love to, but the procedure assumes one has Admin rights to the repo, which I don't :(

**Comment by hacdias** [comment]
@lidel @VictorBjelkholm done. Added the deprecated notes.
